### ISSUE TITLE
Reihenfolge der Parallelgruppen prüfen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#93]
> Wenn man in Campo Parallelgruppen erfasst, werden diese automatisch durchnumeriert. Man gibt die Nummern nicht ein,
sondern diese werden (bei allen Nutzern) vergeben. Man kann aber in Campo nachträglich die Reihenfolge der Parallelgruppen veraendern, indem man zB bei der x. Parallelgruppe sagt, dass diese danach die y. sein soll. Nach einer solchen Verschiebung werden in Campo die Parallelgruppen wieder von 1 an durchnumeriert, d.h. die verschobene Gruppe (und alle nachfolgenden) erhalten eine neue Nummer.

Lt. Rückmeldung DIP sollen die Titel und die Nummerierungen  in der API mit der von Campo übereinstimmen.
Ggf. gibt es hier auch ein Caching-Problem.

vgl. Datenauszug in https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=1096420

**Comment by xwolfde** [comment]
Siehe auch #108

**Comment by thenickless** [comment]
Notiz:

API sortiert nicht per default wie eingeben. Siehe https://github.com/RRZE-Webteam/rrze-lectures/issues/108#issuecomment-1609784578 

=> 2do: sort in request einbauen aber BEACHTEN:

https://github.com/RRZE-Webteam/rrze-lectures/blob/257cb7526bd92992b159054e03a325e4bf741815/includes/Shortcode.php#L188

// we cannot use API parameter "sort" because it sorts per page not the complete dataset -> 2DO: check again, API has changed

**Comment by thenickless** [comment]
done 2.0.15
